coursesApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.CoursesListView.as_view(), name="Courses"),
    path("<slug:slug>", views.CourseDetailView.as_view(), name="course"),
]

django101Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static


# يتم تشغيل هذا الفيو في حال حدوث خطأ 404
handler404 = "django101Project.views.handler404"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="Home"),
    path("settings/", views.Settings.as_view(), name="settings"),
    path("courses/", include("coursesApp.urls")),
    path("about/", views.about, name="About"),
    path("user/<str:username>", views.profile, name="profile"),
    path("registration/", include("registration.urls")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # لعرض وجلب ملفات الميديا

coursesApp/models.py
from django.db import models
from django.db.models.fields import PositiveSmallIntegerField
from django.core.validators import MaxValueValidator, MinValueValidator

from datetime import datetime
from datetime import timedelta
from pytz import UTC

from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils.text import slugify

from django.contrib.auth.models import User

from past_date2word import past_date2word


class Courses(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=False, help_text="Name of the course.")
    number = PositiveSmallIntegerField(
        null=False,
        validators=[MinValueValidator(101), MaxValueValidator(10000)],
        help_text="Number of the course.",
    )
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(
        auto_now_add=True, help_text="Date of adding the course."
    )
    description = models.TextField(
        max_length=325, help_text="Description of the course.", blank=True, null=True
    )

    def is_new(self):
        return self.timestamp >= (datetime.now(tz=UTC) - timedelta(1))

    def creation_time(self):
        return past_date2word(self.timestamp)

    def description_or_nothing(self):
        return self.description or ""

    def __str__(self):
        return f"{self.name} - {self.number}"


@receiver(post_save, sender=Courses)
def make_slug(sender, instance, created, **kwargs):
    if created:
        slug = slugify(f"{instance.name} {instance.number}")
        instance.slug = slug
        instance.save()

templates/user/user-profile.html
{% extends "base.html" %}

{% block title %} {{ user.username }} profile {% endblock title %}



{% block style %}

<style>
    .height-100 {
        height: 100vh
    }

    .card {
        width: 380px;
        border: none
    }

    .dots {
        height: 20px;
        width: 20px;
        margin-top: 4px;
        margin-left: 4px;
        background-color: #343a40;
        border-radius: 50%;
        border: 2px solid #fff;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #fff;
        font-size: 10px
    }

    .list li {
        display: flex;
        justify-content: space-between;
        padding: 13px;
        border-top: 1px solid #eee;
        cursor: pointer
    }

    .list li:hover {
        background-color: #6c757d;
        color: #fff
    }

    a, a:hover{
        color: black;
        text-decoration: none;
    }


</style>

{% endblock style %}



{% block content %}

    <div class="text-center">
        <div class="mt-4">
            <div> <img src="{{user.profile.avatar}}" class="rounded-circle" width="80" height="80"> </div>
            <div class="mt-3 d-flex flex-row justify-content-center">
                <h5>@{{user.username}}</h5>
                <!--  <span class="dots"><i class="fa fa-check"></i></span> -->
            </div>
            <div class="mt-2">
                <span>
                    {{ user.date_joined|date}}
                </span>
                <p>
                    {{user.profile.get_bio}}
                </p>
            </div>
            <div class="mt-3 mb-3">
                <button class="btn btn-secondary" disabled >Follow</button>
                <span class="ml-2"><i class="fa fa-users mr-1"></i>0</span>
            </div>
        </div>
    </div>
        <div class="container">
            <div class="card bg-secondary" style="min-width: 100%;">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item"> <a class="nav-link active bg-secondary" data-toggle="tab" href="#courses" role="tab" aria-expanded="true" style="color:#fff;">Courses</a> </li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane active" id="courses" role="tabpanel" aria-expanded="true">
                        <div class="card-block mt-3 ml-3 mb-3 mr-3">
                            <div>
                                <div class="list-group">
                                    {% for course in user.courses_set.all %}
                                        <a href="{% url 'course' slug=course.slug %}" class="list-group-item list-group-item-action list-group-item-dark mb-2">
                                            {{course.name}} <small class="text-muted">{{ course.creation_time }}</small>
                                            <br>
                                            <small>{{course.number}}</small>
                                        </a>
                                    {% empty %}
                                        <h5 class="text-white">
                                            <i class="fa fa-exclamation" aria-hidden="true"></i>
                                            No course has been published from this user.
                                        </h5>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}

templates/user/user-settings.html
{% extends "base.html" %}
{% load key %}
{% block title %} {{ user.username }} setting {% endblock title %}


{% block content %}

<div class="container">
    <div class="card bg-dark" style="min-width: 100%; margin-top: 60px;">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active bg-dark" data-toggle="tab" href="#updateProfile" role="tab" aria-expanded="true" style="color:#fff;">
                    Update Profile
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link bg-dark" data-toggle="tab" href="#changePassword" role="tab" aria-expanded="true" style="color:#fff;">
                    Change Password
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link bg-dark" data-toggle="tab" href="#deleteAccount" role="tab" aria-expanded="true" style="color:#fff;">
                    Delete Account
                </a>
            </li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="updateProfile" role="tabpanel" aria-expanded="true">
                <div class="card-block mt-3 ml-3 mb-3 mr-3">
                    <div>
                        <div class="d-flex align-items-center justify-content-center">
                            <div class="mt-5">
                                <div>
                                    <div class="d-flex justify-content-between">
                                        <img src="{{user.profile.avatar}}" class="rounded" width="100">
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <form action="{% url 'settings' %}?form=update_profile" method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {% for form in profile_forms %}
                                            {% for input in form %}
                                                <div class="row">
                                                    <div class="col-6">
                                                        <div class="inputbox mt-3">
                                                            {{input}}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        {% endfor %}
                                        <div class="mt-3">
                                            <button type="submit" class="btn btn-success">Updatee</button>
                                            <a href="/" class="btn btn-secondary">Back</a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="changePassword" role="tabpanel" aria-expanded="true">
                <div class="card-block mt-3 ml-3 mb-3 mr-3">
                    <div>
                        <div class="d-flex align-items-center justify-content-center">
                            <div class="mt-5">
                                <div class="mt-3">
                                    <form action="{% url 'settings' %}?form=update_password" method="POST">
                                        {% csrf_token %}
                                        {% if password_form.errors %}
                                            <div class="border border-danger" style="max-width:400px">
                                                <p>
                                                    {% for error in password_form.errors %}
                                                        <ul class="list-group ml-3 mr-3">
                                                            {% for text in password_form.errors|key:error %}
                                                                <li class="list-group-item list-group-item-danger mt-1">
                                                                    {{text}}
                                                                </li>
                                                            {% endfor %}
                                                        </ul>
                                                    {% endfor %}
                                                </p>
                                            </div>
                                        {% endif %}
                                        {% for input in password_form %}
                                            <div class="ro ml-3">
                                                <div class="inputbox mt-3">
                                                    <h5 style="color: white">{{input.label}}</h5>
                                                    {{input}}
                                                </div>
                                            </div>
                                        {% endfor %}
                                        <div class="mt-4 ml-3">
                                            <button type="submit" class="btn btn-success">Updatee</button>
                                            <a href="/" class="btn btn-secondary">Back</a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="deleteAccount" role="tabpanel" aria-expanded="true">
                <div class="card-block mt-3 ml-3 mb-3 mr-3">
                    <div>
                        <div class="d-flex align-items-center justify-content-center">
                            <div class="mt-5">
                                <div class="mt-3">
                                    <div class="text-danger">
                                        <h2>
                                            Delete Account.
                                        </h2>
                                        <button type="button" 
                                                class="btn-text-right btn btn-danger"
                                                data-toggle="modal" 
                                                data-target="#deleteModal" >
                                                Delete
                                        </button>
                                    </div>
                                    <div class="modal fade show" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content dark-modal">
                                                <div class="modal-header">
                                                    <h3 class="modal-title" id="formModalLabel">Are you sure you want to delete your account?</h3>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <form action="{% url 'settings' %}?form=delete_account" method="POST">
                                                    {% csrf_token %}
                                                    <div class="modal-body">
                                                        You can never undo this option, and all your data will be deleted and you will not be able to recover it.
                                                    </div>
                                                    <div class="modal-footer d-flex justify-content-center">
                                                        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}